import { Grid, Stack, Typography } from '@mui/material';
import Head from 'next/head';

export default function Home() {
	return (
		<Grid>
			<Head>
				<title>Rewiles</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Stack
					height="100vh"
					justifyContent="center"
					alignItems="center"
					gap={4}
				>
					<Typography variant="h1">Welcome to Rewiles</Typography>
				</Stack>
			</main>
		</Grid>
	);
}
