import Head from 'next/head';
import { FC, ReactNode } from 'react';
import Footer from './Navigation/Footer';
import NavigationBar from './Navigation/NavigationBar';

type Props = {
  children: ReactNode;
}

const Layout: FC<Props> = ({children}) => {
	return (
		<div>
			<Head>
				<title>Rewiles</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<NavigationBar />
			<main>
				{children}
			</main>
			<Footer />
		</div>
	);
};

export default Layout;