import { Grid, Stack, Typography } from '@mui/material';
import { GetStaticPaths, GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import { IHomeWordings, en, es } from '@/locales';

type Props = {
  wordings: IHomeWordings
}

// eslint-disable-next-line react/prop-types
const Home: NextPage<Props> = ({ wordings }) => {
	return (
		<Grid>
			<Head>
				<title>Rewiles</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<pre>
					{JSON.stringify(wordings, null, 2)}
				</pre>
				<Stack
					height="100vh"
					justifyContent="center"
					alignItems="center"
					gap={4}
				>
					<Typography variant="h1">Welcome to Rewiles</Typography>
				</Stack>
			</main>
		</Grid>
	);
};

export default Home;

// Captures the information needed for the static page
export const getStaticProps: GetStaticProps = async (ctx) => {
	const lang = ctx.params?.lang || 'en'; 
  
	// Returns the properties used in the main component: the page
	return {
		props: {
			locale: ctx.params?.lang || 'en', // Captures the language of [lang] route
			wordings: lang === 'en' ? en : es,
		},
	};
};

// Generates static files on export
export const getStaticPaths: GetStaticPaths = async () => {
	// All supported languages must be listed in 'paths'.
	// If not informed, the static page will not be generated.
	return {
		paths: [{ params: { lang: 'en' } }, { params: { lang: 'es' } }],
		fallback: false,
	};
};
